name: Run Tests

on: push
jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest


  deploy:
      needs: run-test
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to VPS
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            debug: true
            script: echo "hello" | 
              cd /home/farm
              git pull origin main
              systemctl restart farm.service
              systemctl status farm
